#!/usr/bin/env python3
"""Turn the benchmark CSVs into paper-ready tables.

  python3 src/make_paper_tables.py --results results --out paper_tables.md

One row per input, one column per tool, ratios plus the best-baseline margin.
Rows whose round trip did not verify are flagged rather than dropped.
"""
import argparse
import csv
import os
from collections import defaultdict, OrderedDict

NYX = {"nyx", "nyx_vcf"}


def load(path):
    if not os.path.exists(path):
        return []
    with open(path, newline="") as fh:
        return list(csv.DictReader(fh))


def num(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def table(rows, title, out):
    if not rows:
        return
    by_file = OrderedDict()
    tools = []
    for r in rows:
        f = r["file"].strip('"')
        by_file.setdefault(f, {})[r["tool"]] = r
        if r["tool"] not in tools:
            tools.append(r["tool"])
    # NYX first, then the baselines in the order they appear
    tools = [t for t in tools if t in NYX] + [t for t in tools if t not in NYX]

    out.write(f"\n## {title}\n\n")
    hdr = ["input", "size (GB)"]
    if any("archetype" in r for r in rows):
        hdr.insert(1, "archetype")
    hdr += [t for t in tools] + ["NYX / best baseline"]
    out.write("| " + " | ".join(hdr) + " |\n")
    out.write("|" + "|".join(["---"] * len(hdr)) + "|\n")

    for f, per in by_file.items():
        any_row = next(iter(per.values()))
        size = num(any_row.get("orig_bytes")) or 0
        cells = [f]
        if "archetype" in any_row:
            cells.append(any_row.get("archetype", ""))
        cells.append(f"{size/1e9:.2f}")
        ratios = {}
        # Two passes: the winner cannot be known until every ratio is read.
        vals = {}
        for t in tools:
            r = per.get(t)
            if not r:
                continue
            v, cb = num(r.get("ratio")), num(r.get("comp_bytes"))
            if v and cb:
                vals[t] = v
        best = max(vals.values(), default=None)
        for t in tools:
            r = per.get(t)
            if not r:
                cells.append("—")
                continue
            v = vals.get(t)
            if v is None:
                # a tool that produced nothing on this input (bcftools rejects
                # some VCFs outright) is a failure, not a ratio of zero
                cells.append("failed")
                continue
            ratios[t] = v
            mark = "" if r.get("roundtrip", "OK") in ("OK", "", "LOSSY_FORMAT") else " ⚠"
            # Bold marks the best ratio in the row, whoever got it. Bolding our
            # column unconditionally made a losing number look like a winning one.
            cells.append(f"**{v:.2f}×**{mark}" if v == best else f"{v:.2f}×{mark}")
        ours = next((ratios[t] for t in tools if t in NYX and t in ratios), None)
        base = [ratios[t] for t in ratios if t not in NYX]
        # Ratio of ratios: >1 means NYX compresses smaller. Losses are marked so
        # the table cannot be skim-read as a clean sweep.
        if ours and base:
            r = ours / max(base)
            cells.append(f"{r:.2f}" if r >= 1.0 else f"{r:.2f} (loses)")
        else:
            cells.append("—")
        out.write("| " + " | ".join(cells) + " |\n")

    n_win = sum(1 for f, per in by_file.items()
                if (lambda o, b: o and b and o > b)(
                    next((num(per[t].get("ratio")) for t in per if t in NYX), None),
                    max([num(per[t].get("ratio")) or 0 for t in per if t not in NYX] or [0])))
    out.write(f"\nNYX gives the highest ratio on {n_win} of {len(by_file)} inputs.\n")

    notes = sorted({r["tool"] for r in rows
                    if r.get("roundtrip") not in ("OK", "", "LOSSY_FORMAT")})
    if notes:
        out.write(f"\n⚠ round trip not byte-exact: {', '.join(notes)}\n")
    if any(r.get("roundtrip") == "LOSSY_FORMAT" for r in rows):
        out.write("\nBCF is a different container, so a byte comparison against the "
                  "source VCF does not apply; its ratio is against the same "
                  "decompressed VCF as every other row.\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results")
    ap.add_argument("--out", default="results/paper_tables.md")
    a = ap.parse_args()
    with open(a.out, "w") as out:
        out.write("# NYX benchmark tables\n")
        out.write("\nGenerated by `src/make_paper_tables.py` from the CSVs in "
                  "`results/`. Every NYX row is paired with a full decompression "
                  "and byte comparison against the input.\n")
        table(load(os.path.join(a.results, "vcf_bench.csv")), "VCF", out)
        table(load(os.path.join(a.results, "fasta_bench.csv")), "FASTA", out)
        table(load(os.path.join(a.results, "fastq_bench.csv")), "FASTQ", out)
        table(load(os.path.join(a.results, "bed_bench.csv")), "BED", out)
        abl = load(os.path.join(a.results, "vcf_ablation.csv"))
        if abl:
            out.write("\n## VCF: what each transform is worth\n\n")
            stages, per = [], defaultdict(dict)
            for r in abl:
                if r["stage"] not in stages:
                    stages.append(r["stage"])
                per[r["file"].strip('"')][r["stage"]] = num(r.get("ratio"))
            out.write("| stage | " + " | ".join(per) + " |\n")
            out.write("|" + "|".join(["---"] * (len(per) + 1)) + "|\n")
            for s in stages:
                out.write("| " + s + " | " +
                          " | ".join(f"{per[f].get(s):.2f}×" if per[f].get(s) else "—"
                                     for f in per) + " |\n")
    print("wrote", a.out)


if __name__ == "__main__":
    main()
