#!/usr/bin/env python3
"""
Preprocess script generator.

Takes analysis stats and produces a standalone Python preprocessing script
that converts the detected format into binary chunks matching the generated
SDDL schema.

Usage:
    python3 preprocess_generator.py <input_file> [--output-dir DIR]
"""

import argparse
import os
import sys
import textwrap
from pathlib import Path
from typing import Any, Dict

sys.path.insert(0, str(Path(__file__).parent))

from analyzer import analyze
from sddl_generator import safe_output_path


# ---------------------------------------------------------------------------
# Format-specific preprocess script generators
# ---------------------------------------------------------------------------

def generate_fasta_preprocess(stats: Dict[str, Any]) -> str:
    """Generate preprocessing script for FASTA files."""
    n_ratio = stats.get("n_ratio", 0)

    return textwrap.dedent('''\
        #!/usr/bin/env python3
        """
        Preprocessor: FASTA -> FAV4 binary chunks
        Generated by sddl-generate skill

        Borrowed baseline idea from nyx/nyx/core/preprocessor.py:
          - Subprocess wrapper pattern for integration with nyx CLI
          - Chunk file naming: chunk_NNNNN.<format>.bin
          - Sorted glob collection of output chunks

        Borrowed baseline idea from genomic_preprocessor.cpp (FAV4 path):
          - SoA columnar layout: separate header and sequence streams
          - 4-bit base packing with explicit seq_lengths for odd-length restore
          - Offset arrays as prefix sums (N+1 entries)
          - 4-byte aligned padding on all payload sections

        Changed: Pure Python implementation (no C++ dependency required).
          Streaming line-by-line to handle GB-scale files.
        '''
        f'  N-base ratio in sample: {n_ratio}'
        '''
        """

        import argparse
        import struct
        import sys
        from pathlib import Path
        from typing import BinaryIO, List, Tuple

        MAGIC = b"FAV4"
        MAX_CHUNK_BYTES = 450 * 1024 * 1024  # 450 MiB
        ALIGN = 4

        # 4-bit base packing: A=0, C=1, G=2, T=3, N=4
        BASE_PACK = {
            'A': 0, 'a': 0, 'C': 1, 'c': 1,
            'G': 2, 'g': 2, 'T': 3, 't': 3,
            'N': 4, 'n': 4,
        }


        def pad_size(size: int, alignment: int = ALIGN) -> int:
            rem = size % alignment
            return (alignment - rem) % alignment if rem else 0


        def write_u32(f: BinaryIO, val: int) -> None:
            f.write(struct.pack("<I", val))


        def pack_bases(seq: str) -> Tuple[bytes, int]:
            """Pack a DNA sequence into 4-bit nibbles, 2 bases per byte.

            Returns (packed_bytes, original_length).
            """
            length = len(seq)
            packed = bytearray()
            for i in range(0, length, 2):
                high = BASE_PACK.get(seq[i], 4) & 0xF
                low = (BASE_PACK.get(seq[i + 1], 4) & 0xF) if i + 1 < length else 0
                packed.append((high << 4) | low)
            return bytes(packed), length


        def read_fasta_records(path: Path):
            """Yield (header, sequence) tuples from a FASTA file.

            Streaming: reads line-by-line, never loads entire file.
            """
            header = None
            seq_parts: List[str] = []

            with open(path, "r", errors="replace") as f:
                for line in f:
                    line = line.rstrip("\\n\\r")
                    if line.startswith(">"):
                        if header is not None:
                            yield header, "".join(seq_parts)
                        header = line[1:]  # strip >
                        seq_parts = []
                    else:
                        seq_parts.append(line)

            if header is not None:
                yield header, "".join(seq_parts)


        def write_chunk(records: List[Tuple[str, str]], chunk_path: Path) -> None:
            """Write records into a FAV4 binary chunk file."""
            hdr_offsets = [0]
            seq_offsets = [0]
            seq_lengths = []
            all_headers = bytearray()
            all_sequences = bytearray()

            for header, sequence in records:
                hdr_bytes = header.encode("utf-8", errors="replace")
                all_headers.extend(hdr_bytes)
                hdr_offsets.append(len(all_headers))

                packed, orig_len = pack_bases(sequence)
                all_sequences.extend(packed)
                seq_offsets.append(len(all_sequences))
                seq_lengths.append(orig_len)

            num_records = len(records)
            hdr_total = len(all_headers)
            seq_total = len(all_sequences)
            hdr_pad = pad_size(hdr_total)
            seq_pad = pad_size(seq_total)

            with open(chunk_path, "wb") as f:
                f.write(MAGIC)
                write_u32(f, num_records)

                for off in hdr_offsets:
                    write_u32(f, off)
                for off in seq_offsets:
                    write_u32(f, off)
                for sl in seq_lengths:
                    write_u32(f, sl)

                write_u32(f, hdr_total)
                write_u32(f, seq_total)
                write_u32(f, hdr_pad)
                write_u32(f, seq_pad)

                f.write(all_headers)
                if hdr_pad:
                    f.write(b"\\x00" * hdr_pad)

                f.write(all_sequences)
                if seq_pad:
                    f.write(b"\\x00" * seq_pad)


        def preprocess(input_path: Path, output_dir: Path, threads: int = 1) -> List[Path]:
            """Main entry: reads FASTA, splits into chunks, writes binary files."""
            output_dir.mkdir(parents=True, exist_ok=True)
            chunks_written: List[Path] = []

            current_records: List[Tuple[str, str]] = []
            current_size = 0
            chunk_index = 0

            for header, sequence in read_fasta_records(input_path):
                record_size = len(header) + len(sequence)
                if current_size + record_size > MAX_CHUNK_BYTES and current_records:
                    chunk_path = output_dir / f"chunk_{chunk_index:05d}.fasta_packed.bin"
                    write_chunk(current_records, chunk_path)
                    chunks_written.append(chunk_path)
                    chunk_index += 1
                    current_records = []
                    current_size = 0

                current_records.append((header, sequence))
                current_size += record_size

            if current_records:
                chunk_path = output_dir / f"chunk_{chunk_index:05d}.fasta_packed.bin"
                write_chunk(current_records, chunk_path)
                chunks_written.append(chunk_path)

            return sorted(chunks_written)


        def main():
            parser = argparse.ArgumentParser(
                description="Preprocess FASTA files into FAV4 binary chunks for OpenZL"
            )
            parser.add_argument("input", type=Path, help="Input FASTA file")
            parser.add_argument("output_dir", type=Path, help="Output directory")
            parser.add_argument("--threads", type=int, default=1)
            args = parser.parse_args()

            if not args.input.exists():
                print(f"Error: {args.input} not found", file=sys.stderr)
                sys.exit(1)

            chunks = preprocess(args.input, args.output_dir, args.threads)
            print(f"Wrote {len(chunks)} chunk(s) to {args.output_dir}")
            for c in chunks:
                print(f"  {c}")


        if __name__ == "__main__":
            main()
    ''')


def generate_fastq_preprocess(stats: Dict[str, Any]) -> str:
    """Generate preprocessing script for FASTQ files."""
    common_prefix = stats.get("common_header_prefix", "")

    return textwrap.dedent('''\
        #!/usr/bin/env python3
        """
        Preprocessor: FASTQ -> FQV5 binary chunks
        Generated by sddl-generate skill

        Borrowed baseline idea from nyx/nyx/core/preprocessor.py:
          - Subprocess wrapper pattern, chunk naming convention

        Borrowed baseline idea from genomic_preprocessor.cpp (FQV4 path):
          - Header common-prefix deduplication
          - 4-bit sequence packing
          - Separate quality stream

        Changed: Pure Python streaming implementation.
          Added offset arrays for all variable-length fields
          because SDDL docs recommend explicit sizes over delimiters.
        '''
        f'  Detected common header prefix: "{common_prefix[:40]}"'
        '''
        """

        import argparse
        import struct
        import sys
        from pathlib import Path
        from typing import BinaryIO, List, Tuple

        MAGIC = b"FQV5"
        MAX_CHUNK_BYTES = 450 * 1024 * 1024
        ALIGN = 4

        BASE_PACK = {
            'A': 0, 'a': 0, 'C': 1, 'c': 1,
            'G': 2, 'g': 2, 'T': 3, 't': 3,
            'N': 4, 'n': 4,
        }


        def pad_size(size, alignment=ALIGN):
            rem = size % alignment
            return (alignment - rem) % alignment if rem else 0


        def write_u32(f, val):
            f.write(struct.pack("<I", val))


        def write_u16(f, val):
            f.write(struct.pack("<H", val))


        def pack_bases(seq):
            length = len(seq)
            packed = bytearray()
            for i in range(0, length, 2):
                high = BASE_PACK.get(seq[i], 4) & 0xF
                low = (BASE_PACK.get(seq[i + 1], 4) & 0xF) if i + 1 < length else 0
                packed.append((high << 4) | low)
            return bytes(packed), length


        def compute_common_prefix(path, max_records=10000):
            """Compute common header prefix from first N records."""
            prefix = None
            count = 0
            with open(path, "r", errors="replace") as f:
                for line in f:
                    line = line.rstrip("\\n\\r")
                    if line.startswith("@"):
                        if prefix is None:
                            prefix = line
                        else:
                            i = 0
                            while i < len(prefix) and i < len(line) and prefix[i] == line[i]:
                                i += 1
                            prefix = prefix[:i]
                            if not prefix:
                                break
                        count += 1
                        if count >= max_records:
                            break
            return prefix or ""


        def read_fastq_records(path):
            """Yield (header, sequence, quality) tuples."""
            with open(path, "r", errors="replace") as f:
                while True:
                    h = f.readline()
                    if not h:
                        break
                    s = f.readline()
                    p = f.readline()
                    q = f.readline()
                    if not q:
                        break
                    yield (
                        h.rstrip("\\n\\r"),
                        s.rstrip("\\n\\r"),
                        q.rstrip("\\n\\r"),
                    )


        def write_chunk(records, chunk_path, common_prefix):
            """Write records into an FQV5 binary chunk file."""
            prefix_bytes = common_prefix.encode("utf-8", errors="replace")
            prefix_len = len(prefix_bytes)

            suffix_offsets = [0]
            seq_offsets = [0]
            qual_offsets = [0]
            read_lengths = []
            all_suffixes = bytearray()
            all_sequences = bytearray()
            all_qualities = bytearray()

            for header, sequence, quality in records:
                # Suffix = header minus common prefix
                if header.startswith(common_prefix):
                    suffix = header[len(common_prefix):]
                else:
                    suffix = header
                suffix_bytes = suffix.encode("utf-8", errors="replace")
                all_suffixes.extend(suffix_bytes)
                suffix_offsets.append(len(all_suffixes))

                packed, orig_len = pack_bases(sequence)
                all_sequences.extend(packed)
                seq_offsets.append(len(all_sequences))
                read_lengths.append(orig_len)

                qual_bytes = quality.encode("ascii", errors="replace")
                all_qualities.extend(qual_bytes)
                qual_offsets.append(len(all_qualities))

            num_records = len(records)
            suffix_total = len(all_suffixes)
            seq_total = len(all_sequences)
            qual_total = len(all_qualities)
            suffix_pad = pad_size(suffix_total)
            seq_pad = pad_size(seq_total)
            qual_pad = pad_size(qual_total)

            with open(chunk_path, "wb") as f:
                f.write(MAGIC)
                write_u32(f, num_records)

                write_u16(f, prefix_len)
                if prefix_len:
                    f.write(prefix_bytes)

                for rl in read_lengths:
                    write_u16(f, rl)

                for off in suffix_offsets:
                    write_u32(f, off)
                for off in seq_offsets:
                    write_u32(f, off)
                for off in qual_offsets:
                    write_u32(f, off)

                write_u32(f, suffix_total)
                write_u32(f, seq_total)
                write_u32(f, qual_total)
                write_u32(f, suffix_pad)
                write_u32(f, seq_pad)
                write_u32(f, qual_pad)

                f.write(all_suffixes)
                if suffix_pad:
                    f.write(b"\\x00" * suffix_pad)
                f.write(all_sequences)
                if seq_pad:
                    f.write(b"\\x00" * seq_pad)
                f.write(all_qualities)
                if qual_pad:
                    f.write(b"\\x00" * qual_pad)


        def preprocess(input_path, output_dir, threads=1):
            output_dir.mkdir(parents=True, exist_ok=True)
            common_prefix = compute_common_prefix(input_path)
            chunks_written = []
            current_records = []
            current_size = 0
            chunk_index = 0

            for header, sequence, quality in read_fastq_records(input_path):
                record_size = len(header) + len(sequence) + len(quality)
                if current_size + record_size > MAX_CHUNK_BYTES and current_records:
                    chunk_path = output_dir / f"chunk_{chunk_index:05d}.fastq_v5.bin"
                    write_chunk(current_records, chunk_path, common_prefix)
                    chunks_written.append(chunk_path)
                    chunk_index += 1
                    current_records = []
                    current_size = 0

                current_records.append((header, sequence, quality))
                current_size += record_size

            if current_records:
                chunk_path = output_dir / f"chunk_{chunk_index:05d}.fastq_v5.bin"
                write_chunk(current_records, chunk_path, common_prefix)
                chunks_written.append(chunk_path)

            return sorted(chunks_written)


        def main():
            parser = argparse.ArgumentParser(description="Preprocess FASTQ -> FQV5 binary")
            parser.add_argument("input", type=Path)
            parser.add_argument("output_dir", type=Path)
            parser.add_argument("--threads", type=int, default=1)
            args = parser.parse_args()

            if not args.input.exists():
                print(f"Error: {args.input} not found", file=sys.stderr)
                sys.exit(1)

            chunks = preprocess(args.input, args.output_dir, args.threads)
            print(f"Wrote {len(chunks)} chunk(s) to {args.output_dir}")
            for c in chunks:
                print(f"  {c}")


        if __name__ == "__main__":
            main()
    ''')


def generate_vcf_preprocess(stats: Dict[str, Any]) -> str:
    """Generate preprocessing script for VCF files."""
    return textwrap.dedent('''\
        #!/usr/bin/env python3
        """
        Preprocessor: VCF -> VCF4 binary chunks
        Generated by sddl-generate skill

        Borrowed baseline idea from genomic_preprocessor.cpp (VCF3 path):
          - Columnar decomposition of VCF columns
          - Dictionary-encoding CHROM and FILTER
          - Separate streams for fixed and variable-width columns

        Changed: Pure Python streaming implementation.
          Using U16 for dictionary IDs (sufficient for typical VCF files).
          Added offset arrays for all variable-length columns.
        """

        import argparse
        import struct
        import sys
        from pathlib import Path
        from typing import BinaryIO, Dict, List, Tuple

        MAGIC = b"VCF4"
        MAX_CHUNK_BYTES = 300 * 1024 * 1024
        ALIGN = 4


        def pad_size(size, alignment=ALIGN):
            rem = size % alignment
            return (alignment - rem) % alignment if rem else 0


        def write_u32(f, val):
            f.write(struct.pack("<I", val))


        def write_u16(f, val):
            f.write(struct.pack("<H", val))


        def parse_vcf_header(path):
            """Parse VCF header, extract CHROM and FILTER dictionaries."""
            raw_header_lines = []
            chrom_dict: Dict[str, int] = {}
            filter_dict: Dict[str, int] = {}

            with open(path, "r", errors="replace") as f:
                for line in f:
                    line = line.rstrip("\\n\\r")
                    if not line.startswith("#"):
                        break
                    raw_header_lines.append(line)

                    if line.startswith("##contig=<"):
                        idx = line.find("ID=")
                        if idx >= 0:
                            end = line.find(",", idx)
                            if end < 0:
                                end = line.find(">", idx)
                            chrom = line[idx + 3:end]
                            if chrom not in chrom_dict:
                                chrom_dict[chrom] = len(chrom_dict)

                    elif line.startswith("##FILTER=<"):
                        idx = line.find("ID=")
                        if idx >= 0:
                            end = line.find(",", idx)
                            if end < 0:
                                end = line.find(">", idx)
                            filt = line[idx + 3:end]
                            if filt not in filter_dict:
                                filter_dict[filt] = len(filter_dict)

            for default in ("PASS", "."):
                if default not in filter_dict:
                    filter_dict[default] = len(filter_dict)

            raw_header = "\\n".join(raw_header_lines)
            return raw_header, chrom_dict, filter_dict


        def read_vcf_records(path):
            """Yield VCF data rows as column lists."""
            with open(path, "r", errors="replace") as f:
                for line in f:
                    line = line.rstrip("\\n\\r")
                    if line.startswith("#"):
                        continue
                    cols = line.split("\\t")
                    if len(cols) >= 8:
                        yield cols


        def write_chunk(records, chunk_path, raw_header, chrom_dict, filter_dict):
            """Write VCF records into a VCF4 binary chunk."""
            chrom_ids = []
            positions = []
            filter_ids = []

            id_offsets, ref_offsets, alt_offsets = [0], [0], [0]
            qual_offsets, info_offsets, gt_offsets = [0], [0], [0]

            id_data = bytearray()
            ref_data = bytearray()
            alt_data = bytearray()
            qual_data = bytearray()
            info_data = bytearray()
            gt_data = bytearray()

            has_gt = False

            for cols in records:
                chrom_ids.append(chrom_dict.get(cols[0], 0))
                try:
                    positions.append(int(cols[1]))
                except ValueError:
                    positions.append(0)
                filter_ids.append(filter_dict.get(cols[6], 0))

                id_data.extend(cols[2].encode("utf-8"))
                id_offsets.append(len(id_data))
                ref_data.extend(cols[3].encode("utf-8"))
                ref_offsets.append(len(ref_data))
                alt_data.extend(cols[4].encode("utf-8"))
                alt_offsets.append(len(alt_data))
                qual_data.extend(cols[5].encode("utf-8"))
                qual_offsets.append(len(qual_data))
                info_data.extend(cols[7].encode("utf-8"))
                info_offsets.append(len(info_data))

                if len(cols) > 8:
                    has_gt = True
                    gt_str = "\\t".join(cols[8:])
                    gt_data.extend(gt_str.encode("utf-8"))
                gt_offsets.append(len(gt_data))

            num_records = len(records)
            header_bytes = raw_header.encode("utf-8")
            header_len = len(header_bytes)
            header_pad_n = pad_size(header_len)

            with open(chunk_path, "wb") as f:
                f.write(MAGIC)

                write_u32(f, header_len)
                write_u32(f, header_pad_n)
                f.write(header_bytes)
                if header_pad_n:
                    f.write(b"\\x00" * header_pad_n)

                write_u32(f, num_records)

                for cid in chrom_ids:
                    write_u16(f, cid)
                for pos in positions:
                    write_u32(f, pos)
                for fid in filter_ids:
                    write_u16(f, fid)

                for arrays in [id_offsets, ref_offsets, alt_offsets,
                               qual_offsets, info_offsets, gt_offsets]:
                    for off in arrays:
                        write_u32(f, off)

                blobs = [
                    ("id", id_data), ("ref", ref_data), ("alt", alt_data),
                    ("qual", qual_data), ("info", info_data), ("gt", gt_data),
                ]
                for name, data in blobs:
                    total = len(data)
                    p = pad_size(total)
                    write_u32(f, total)

                for name, data in blobs:
                    total = len(data)
                    p = pad_size(total)
                    write_u32(f, p)

                for name, data in blobs:
                    total = len(data)
                    p = pad_size(total)
                    f.write(data)
                    if p:
                        f.write(b"\\x00" * p)


        def preprocess(input_path, output_dir, threads=1):
            output_dir.mkdir(parents=True, exist_ok=True)
            raw_header, chrom_dict, filter_dict = parse_vcf_header(input_path)

            chunks_written = []
            current_records = []
            current_size = 0
            chunk_index = 0

            for cols in read_vcf_records(input_path):
                record_size = sum(len(c) for c in cols)
                if current_size + record_size > MAX_CHUNK_BYTES and current_records:
                    chunk_path = output_dir / f"chunk_{chunk_index:05d}.vcf4.bin"
                    write_chunk(current_records, chunk_path, raw_header, chrom_dict, filter_dict)
                    chunks_written.append(chunk_path)
                    chunk_index += 1
                    current_records = []
                    current_size = 0

                current_records.append(cols)
                current_size += record_size

            if current_records:
                chunk_path = output_dir / f"chunk_{chunk_index:05d}.vcf4.bin"
                write_chunk(current_records, chunk_path, raw_header, chrom_dict, filter_dict)
                chunks_written.append(chunk_path)

            return sorted(chunks_written)


        def main():
            parser = argparse.ArgumentParser(description="Preprocess VCF -> VCF4 binary")
            parser.add_argument("input", type=Path)
            parser.add_argument("output_dir", type=Path)
            parser.add_argument("--threads", type=int, default=1)
            args = parser.parse_args()

            if not args.input.exists():
                print(f"Error: {args.input} not found", file=sys.stderr)
                sys.exit(1)

            chunks = preprocess(args.input, args.output_dir, args.threads)
            print(f"Wrote {len(chunks)} chunk(s) to {args.output_dir}")
            for c in chunks:
                print(f"  {c}")


        if __name__ == "__main__":
            main()
    ''')


def generate_tsv_preprocess(stats: Dict[str, Any]) -> str:
    """Generate preprocessing script for TSV/CSV files."""
    fmt = stats.get("format", "tsv")
    delim = "\\t" if fmt == "tsv" else ","
    magic = "TSV1" if fmt == "tsv" else "CSV1"
    col_types = stats.get("column_types", {})
    header_row = stats.get("header_row", [])
    columns = stats.get("columns", 0)

    # Build column type config as Python literal
    col_config_lines = []
    for i, name in enumerate(header_row or [f"col_{j}" for j in range(columns)]):
        ctype = col_types.get(name, "string")
        col_config_lines.append(f'    "{name}": "{ctype}",')
    col_config = "\n".join(col_config_lines)

    return textwrap.dedent(f'''\
        #!/usr/bin/env python3
        """
        Preprocessor: {fmt.upper()} -> {magic} binary chunks
        Generated by sddl-generate skill

        Borrowed baseline idea from nyx/schemas/fasta_packed.sddl:
          - SoA columnar layout
          - Offset arrays for variable-length columns

        Changed: Per-column type detection and native encoding.
          Numeric columns stored as binary arrays for better compression.
          String columns use offset + blob pattern.
        """

        import argparse
        import struct
        import sys
        from pathlib import Path
        from typing import List

        MAGIC = b"{magic}"
        MAX_CHUNK_BYTES = 450 * 1024 * 1024
        ALIGN = 4
        DELIMITER = "{delim}"

        COLUMN_TYPES = {{
        {col_config}
        }}


        def pad_size(size, alignment=ALIGN):
            rem = size % alignment
            return (alignment - rem) % alignment if rem else 0


        def write_u32(f, val):
            f.write(struct.pack("<I", val))


        def read_records(path):
            """Yield rows as list of string values."""
            with open(path, "r", errors="replace") as fh:
                header = fh.readline()  # skip header
                for line in fh:
                    line = line.rstrip("\\n\\r")
                    if line:
                        yield line.split(DELIMITER)


        def write_chunk(records, chunk_path, header_row):
            num_records = len(records)
            num_columns = len(header_row)

            # Prepare column data
            col_data = {{}}
            for i, name in enumerate(header_row):
                ctype = COLUMN_TYPES.get(name, "string")
                if ctype == "int":
                    col_data[name] = [int(r[i]) if i < len(r) and r[i] not in ("", ".", "NA") else 0
                                      for r in records]
                elif ctype == "float":
                    col_data[name] = [float(r[i]) if i < len(r) and r[i] not in ("", ".", "NA") else 0.0
                                      for r in records]
                else:
                    col_data[name] = [r[i] if i < len(r) else "" for r in records]

            header_str = DELIMITER.join(header_row)
            header_bytes = header_str.encode("utf-8")

            with open(chunk_path, "wb") as f:
                f.write(MAGIC)
                write_u32(f, num_records)
                write_u32(f, num_columns)

                # Header row
                h_total = len(header_bytes)
                h_pad = pad_size(h_total)
                write_u32(f, h_total)
                write_u32(f, h_pad)
                f.write(header_bytes)
                if h_pad:
                    f.write(b"\\x00" * h_pad)

                # Column data
                for name in header_row:
                    ctype = COLUMN_TYPES.get(name, "string")
                    if ctype == "int":
                        for val in col_data[name]:
                            f.write(struct.pack("<i", val))
                    elif ctype == "float":
                        for val in col_data[name]:
                            f.write(struct.pack("<d", val))
                    else:
                        offsets = [0]
                        blob = bytearray()
                        for val in col_data[name]:
                            blob.extend(val.encode("utf-8"))
                            offsets.append(len(blob))
                        total = len(blob)
                        p = pad_size(total)
                        for off in offsets:
                            write_u32(f, off)
                        write_u32(f, total)
                        write_u32(f, p)
                        f.write(blob)
                        if p:
                            f.write(b"\\x00" * p)


        def preprocess(input_path, output_dir, threads=1):
            output_dir.mkdir(parents=True, exist_ok=True)

            # Read header
            with open(input_path, "r") as fh:
                header_line = fh.readline().rstrip("\\n\\r")
            header_row = header_line.split(DELIMITER)

            chunks_written = []
            current_records = []
            current_size = 0
            chunk_index = 0

            for cols in read_records(input_path):
                record_size = sum(len(c) for c in cols)
                if current_size + record_size > MAX_CHUNK_BYTES and current_records:
                    chunk_path = output_dir / f"chunk_{{chunk_index:05d}}.{fmt}1.bin"
                    write_chunk(current_records, chunk_path, header_row)
                    chunks_written.append(chunk_path)
                    chunk_index += 1
                    current_records = []
                    current_size = 0

                current_records.append(cols)
                current_size += record_size

            if current_records:
                chunk_path = output_dir / f"chunk_{{chunk_index:05d}}.{fmt}1.bin"
                write_chunk(current_records, chunk_path, header_row)
                chunks_written.append(chunk_path)

            return sorted(chunks_written)


        def main():
            parser = argparse.ArgumentParser(description="Preprocess {fmt.upper()} -> {magic} binary")
            parser.add_argument("input", type=Path)
            parser.add_argument("output_dir", type=Path)
            parser.add_argument("--threads", type=int, default=1)
            args = parser.parse_args()

            if not args.input.exists():
                print(f"Error: {{args.input}} not found", file=sys.stderr)
                sys.exit(1)

            chunks = preprocess(args.input, args.output_dir, args.threads)
            print(f"Wrote {{len(chunks)}} chunk(s) to {{args.output_dir}}")
            for c in chunks:
                print(f"  {{c}}")


        if __name__ == "__main__":
            main()
    ''')


def generate_generic_preprocess(stats: Dict[str, Any]) -> str:
    """Generate minimal preprocessing for unknown formats."""
    return textwrap.dedent('''\
        #!/usr/bin/env python3
        """
        Preprocessor: Generic -> GEN1 binary chunks
        Generated by sddl-generate skill

        WARNING: No specific format detected. This is a minimal chunked-blob
        preprocessor. Consider using `nyx compress <file> --mode default` instead.

        Borrowed baseline idea from nyx/nyx/core/preprocessor.py:
          - Chunk file naming convention
        """

        import argparse
        import struct
        import sys
        from pathlib import Path
        from typing import List

        MAGIC = b"GEN1"
        MAX_CHUNK_BYTES = 450 * 1024 * 1024
        ALIGN = 4


        def pad_size(size, alignment=ALIGN):
            rem = size % alignment
            return (alignment - rem) % alignment if rem else 0


        def write_u32(f, val):
            f.write(struct.pack("<I", val))


        def preprocess(input_path, output_dir, threads=1):
            output_dir.mkdir(parents=True, exist_ok=True)
            file_size = input_path.stat().st_size
            chunks_written = []
            chunk_index = 0

            with open(input_path, "rb") as f:
                while True:
                    data = f.read(MAX_CHUNK_BYTES)
                    if not data:
                        break
                    chunk_path = output_dir / f"chunk_{chunk_index:05d}.gen1.bin"
                    total = len(data)
                    p = pad_size(total)

                    with open(chunk_path, "wb") as out:
                        out.write(MAGIC)
                        write_u32(out, total)
                        write_u32(out, p)
                        out.write(data)
                        if p:
                            out.write(b"\\x00" * p)

                    chunks_written.append(chunk_path)
                    chunk_index += 1

            return sorted(chunks_written)


        def main():
            parser = argparse.ArgumentParser(description="Preprocess generic -> GEN1 binary")
            parser.add_argument("input", type=Path)
            parser.add_argument("output_dir", type=Path)
            parser.add_argument("--threads", type=int, default=1)
            args = parser.parse_args()

            if not args.input.exists():
                print(f"Error: {args.input} not found", file=sys.stderr)
                sys.exit(1)

            chunks = preprocess(args.input, args.output_dir, args.threads)
            print(f"Wrote {len(chunks)} chunk(s) to {args.output_dir}")
            for c in chunks:
                print(f"  {c}")


        if __name__ == "__main__":
            main()
    ''')


# ---------------------------------------------------------------------------
# Dispatcher
# ---------------------------------------------------------------------------

GENERATORS = {
    "fasta": generate_fasta_preprocess,
    "fastq": generate_fastq_preprocess,
    "vcf": generate_vcf_preprocess,
    "tsv": generate_tsv_preprocess,
    "csv": generate_tsv_preprocess,
    "generic": generate_generic_preprocess,
}


def generate_preprocess(stats: Dict[str, Any]) -> str:
    """Generate preprocessing script content based on analysis stats."""
    fmt = stats.get("format", "generic")
    generator = GENERATORS.get(fmt, generate_generic_preprocess)
    return generator(stats)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Generate preprocessor script")
    parser.add_argument("input", type=Path, help="Input file")
    parser.add_argument("--output-dir", type=Path, default=Path("./sddl_out"))
    parser.add_argument("--sample-bytes", type=int, default=10 * 1024 * 1024)
    args = parser.parse_args()

    if not args.input.exists():
        print(f"Error: {args.input} does not exist", file=sys.stderr)
        sys.exit(1)

    stats = analyze(args.input, args.sample_bytes)
    script_content = generate_preprocess(stats)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    out_path = safe_output_path(args.output_dir, "preprocess", ".py")
    out_path.write_text(script_content)
    os.chmod(str(out_path), 0o755)
    print(f"Wrote preprocessor: {out_path}")
    return str(out_path)


if __name__ == "__main__":
    main()
