#!/usr/bin/env python3
"""
SDDL schema generator.

Takes analysis stats from analyzer.py and produces an optimal SDDL schema
file tailored to the detected format.

Usage:
    python3 sddl_generator.py <input_file> [--output-dir DIR]
"""

import argparse
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

# Allow importing siblings
sys.path.insert(0, str(Path(__file__).parent))

from analyzer import analyze


# ---------------------------------------------------------------------------
# Version-safe output path
# ---------------------------------------------------------------------------

def safe_output_path(output_dir: Path, basename: str, ext: str) -> Path:
    """Find a non-colliding output path, incrementing version if needed."""
    candidate = output_dir / f"{basename}{ext}"
    if not candidate.exists():
        return candidate
    version = 2
    while True:
        candidate = output_dir / f"{basename}_v{version}{ext}"
        if not candidate.exists():
            return candidate
        version += 1


# ---------------------------------------------------------------------------
# Format-specific SDDL generators
# ---------------------------------------------------------------------------

def generate_fasta_sddl(stats: Dict[str, Any]) -> str:
    """Generate SDDL for FASTA files.

    Borrowed baseline idea from nyx/schemas/fasta_packed.sddl:
      - SoA columnar layout with offset arrays
      - 4-bit packed sequences with seq_lengths for odd-length restore
      - Explicit payload sizes + padding for instant-parse
    """
    has_n = stats.get("has_n_bases", True)
    n_ratio = stats.get("n_ratio", 1.0)

    # Decide packing strategy
    if not has_n and n_ratio == 0:
        packing_note = (
            "# Changed: Could use 2-bit packing (4 bases/byte) since no N bases detected.\n"
            "# However, using 4-bit packing for compatibility with existing nyx pipeline.\n"
            "# 4-bit packing: A=0, C=1, G=2, T=3, N=4; 2 bases per byte, high nibble first."
        )
    else:
        packing_note = (
            f"# 4-bit packing: A=0, C=1, G=2, T=3, N=4; 2 bases per byte, high nibble first.\n"
            f"# N-base ratio: {n_ratio} — 4-bit packing required to encode N."
        )

    lines = [
        "# ============================================================",
        "# FASTA Packed Schema (v4)",
        "# Generated by sddl-generate skill",
        "#",
        "# Borrowed baseline idea from nyx/schemas/fasta_packed.sddl:",
        "#   - SoA columnar layout with offset arrays",
        "#   - Explicit payload lengths + padding for instant-parse",
        "#   - Magic header + num_records for instant-parse arrays",
        "#   - seq_lengths array for lossless restore of odd-length sequences",
        "#",
        packing_note,
        "# ============================================================",
        "",
        "U32 = UInt32LE",
        "",
        "# Magic \"FAV4\"",
        "magic       : Byte[4]",
        "num_records : U32",
        "",
        "# Offsets (prefix sums, num_records + 1 entries)",
        "hdr_offsets : U32[num_records + 1]",
        "seq_offsets : U32[num_records + 1]",
        "",
        "# Original sequence lengths (in bases) - needed to restore exact length",
        "seq_lengths : U32[num_records]",
        "",
        "# Payload lengths (unpadded)",
        "hdr_total   : U32",
        "seq_total   : U32",
        "",
        "# Padding",
        "hdr_pad     : U32",
        "seq_pad     : U32",
        "",
        "# Payloads",
        "headers     : Byte[hdr_total + hdr_pad]",
        "sequences   : Byte[seq_total + seq_pad] # Packed 4-bit (2 bases/byte)",
        "",
        ": Byte[_rem]",
    ]
    return "\n".join(lines) + "\n"


def generate_fastq_sddl(stats: Dict[str, Any]) -> str:
    """Generate SDDL for FASTQ files.

    Borrowed baseline idea from nyx/schemas/fasta_packed.sddl:
      - SoA columnar layout with offset arrays
      - Magic + num_records header pattern

    Borrowed baseline idea from genomic_preprocessor.cpp (FQV4 path):
      - Header common-prefix deduplication
      - 4-bit sequence packing
      - Separate quality score stream

    Changed: Added explicit suffix/qual offset arrays and totals
    because docs recommend explicit sizes over delimiter scanning.
    """
    prefix_len = stats.get("common_prefix_len", 0)
    has_n = stats.get("has_n_bases", True)
    fixed_reads = stats.get("fixed_length_reads", False)

    lines = [
        "# ============================================================",
        "# FASTQ Schema (v1)",
        "# Generated by sddl-generate skill",
        "#",
        "# Borrowed baseline idea from nyx/schemas/fasta_packed.sddl:",
        "#   - SoA columnar layout with offset arrays",
        "#   - Explicit payload lengths + padding for instant-parse",
        "#   - Magic + num_records header",
        "#",
        "# Borrowed baseline idea from genomic_preprocessor.cpp (FQV4):",
        "#   - Header common-prefix dedup (prefix stored once, suffixes per-record)",
        "#   - 4-bit sequence packing (A=0,C=1,G=2,T=3,N=4)",
        "#   - Separate quality stream (raw Phred+33 bytes)",
        "#",
        f"# Changed: Using offset arrays for all variable-length fields",
        f"#   because SDDL docs recommend explicit sizes over delimiter scanning.",
        f"# Common header prefix length: {prefix_len} chars (will be deduped)",
        "# ============================================================",
        "",
        "U32 = UInt32LE",
        "U16 = UInt16LE",
        "",
        "# Magic \"FQV5\"",
        "magic         : Byte[4]",
        "num_records   : U32",
        "",
        "# Common header prefix (stored once)",
        "prefix_len    : U16",
        "common_prefix : Byte[prefix_len]",
        "",
        "# Per-record read lengths (in bases, for packed restore)",
        "read_lengths  : U16[num_records]",
        "",
        "# Offset arrays (prefix sums, N+1 entries)",
        "suffix_offsets : U32[num_records + 1]",
        "seq_offsets    : U32[num_records + 1]",
        "qual_offsets   : U32[num_records + 1]",
        "",
        "# Payload totals (unpadded)",
        "suffix_total  : U32",
        "seq_total     : U32",
        "qual_total    : U32",
        "",
        "# Padding",
        "suffix_pad    : U32",
        "seq_pad       : U32",
        "qual_pad      : U32",
        "",
        "# Payloads",
        "suffixes      : Byte[suffix_total + suffix_pad]   # Header suffixes (after common prefix)",
        "sequences     : Byte[seq_total + seq_pad]         # 4-bit packed bases",
        "qualities     : Byte[qual_total + qual_pad]       # Raw Phred+33 quality bytes",
        "",
        ": Byte[_rem]",
    ]
    return "\n".join(lines) + "\n"


def generate_vcf_sddl(stats: Dict[str, Any]) -> str:
    """Generate SDDL for VCF files.

    Borrowed baseline idea from nyx/schemas/fasta_packed.sddl:
      - SoA columnar layout
      - Offset arrays for variable-length fields
      - Magic + num_records header

    Borrowed baseline idea from genomic_preprocessor.cpp (VCF3 path):
      - Columnar decomposition of VCF columns
      - Dictionary-encoding CHROM and FILTER

    Changed: Added separate raw_header block and genotype stream
    because VCF files have variable-width header and optional genotypes.
    """
    has_gt = stats.get("has_genotypes", False)
    n_chroms = stats.get("unique_chroms", 0)
    n_filters = stats.get("unique_filters", 0)

    lines = [
        "# ============================================================",
        "# VCF Schema (v1)",
        "# Generated by sddl-generate skill",
        "#",
        "# Borrowed baseline idea from nyx/schemas/fasta_packed.sddl:",
        "#   - SoA columnar layout with offset arrays",
        "#   - Explicit payload lengths + padding",
        "#",
        "# Borrowed baseline idea from genomic_preprocessor.cpp (VCF3):",
        "#   - Columnar decomposition: CHROM, POS, REF, ALT, etc.",
        "#   - Dictionary-encode CHROM and FILTER to uint IDs",
        "#",
        f"# Changed: Storing raw VCF header as a length-prefixed blob",
        f"#   because VCF headers are variable-width metadata blocks.",
        f"# Detected {n_chroms} chromosomes, {n_filters} filters.",
        f"# Has genotypes: {has_gt}",
        "# ============================================================",
        "",
        "U32 = UInt32LE",
        "U16 = UInt16LE",
        "",
        "# Magic \"VCF4\"",
        "magic         : Byte[4]",
        "",
        "# Raw VCF header (meta-information lines)",
        "header_len    : U32",
        "header_pad    : U32",
        "raw_header    : Byte[header_len + header_pad]",
        "",
        "num_records   : U32",
        "",
        "# Fixed-width columns (SoA layout)",
        "chrom_ids     : U16[num_records]    # Dictionary-encoded chromosome IDs",
        "positions     : U32[num_records]    # POS column",
        "filter_ids    : U16[num_records]    # Dictionary-encoded filter IDs",
        "",
        "# Variable-length columns (offset + blob pattern)",
        "id_offsets    : U32[num_records + 1]",
        "ref_offsets   : U32[num_records + 1]",
        "alt_offsets   : U32[num_records + 1]",
        "qual_offsets  : U32[num_records + 1]",
        "info_offsets  : U32[num_records + 1]",
    ]

    if has_gt:
        lines.append("gt_offsets    : U32[num_records + 1]")

    lines.extend([
        "",
        "# Payload totals",
        "id_total      : U32",
        "ref_total     : U32",
        "alt_total     : U32",
        "qual_total    : U32",
        "info_total    : U32",
    ])
    if has_gt:
        lines.append("gt_total      : U32")

    lines.extend([
        "",
        "# Padding",
        "id_pad        : U32",
        "ref_pad       : U32",
        "alt_pad       : U32",
        "qual_pad      : U32",
        "info_pad      : U32",
    ])
    if has_gt:
        lines.append("gt_pad        : U32")

    lines.extend([
        "",
        "# Payloads",
        "id_data       : Byte[id_total + id_pad]",
        "ref_data      : Byte[ref_total + ref_pad]",
        "alt_data      : Byte[alt_total + alt_pad]",
        "qual_data     : Byte[qual_total + qual_pad]",
        "info_data     : Byte[info_total + info_pad]",
    ])
    if has_gt:
        lines.append("gt_data       : Byte[gt_total + gt_pad]")

    lines.extend(["", ": Byte[_rem]"])
    return "\n".join(lines) + "\n"


def generate_tsv_sddl(stats: Dict[str, Any]) -> str:
    """Generate SDDL for TSV/CSV files."""
    fmt = stats.get("format", "tsv")
    magic = "TSV1" if fmt == "tsv" else "CSV1"
    columns = stats.get("columns", 0)
    col_types = stats.get("column_types", {})
    header_row = stats.get("header_row", [])

    lines = [
        "# ============================================================",
        f"# {fmt.upper()} Schema (v1)",
        "# Generated by sddl-generate skill",
        "#",
        "# Borrowed baseline idea from nyx/schemas/fasta_packed.sddl:",
        "#   - SoA columnar layout",
        "#   - Offset arrays for variable-length columns",
        "#",
        f"# Changed: Per-column typing with {columns} columns detected.",
        "#   Numeric columns stored as native binary arrays.",
        "#   String columns stored as offset + blob.",
        "# ============================================================",
        "",
        "U32 = UInt32LE",
        "",
        f'# Magic "{magic}"',
        "magic         : Byte[4]",
        "num_records   : U32",
        f"num_columns   : U32  # = {columns}",
        "",
        "# Header row (column names)",
        "header_total  : U32",
        "header_pad    : U32",
        "header_data   : Byte[header_total + header_pad]",
        "",
    ]

    # Generate per-column declarations
    for i, col_name in enumerate(header_row or [f"col_{j}" for j in range(columns)]):
        safe_name = col_name.replace(" ", "_").replace("-", "_").lower()[:20]
        col_type = col_types.get(col_name, "string")

        if col_type == "int":
            lines.append(f"# Column {i}: {col_name} (integer)")
            lines.append(f"{safe_name} : Int32LE[num_records]")
        elif col_type == "float":
            lines.append(f"# Column {i}: {col_name} (float)")
            lines.append(f"{safe_name} : Float64LE[num_records]")
        else:
            lines.append(f"# Column {i}: {col_name} (string)")
            lines.append(f"{safe_name}_offsets : U32[num_records + 1]")
            lines.append(f"{safe_name}_total   : U32")
            lines.append(f"{safe_name}_pad     : U32")
            lines.append(f"{safe_name}_data    : Byte[{safe_name}_total + {safe_name}_pad]")
        lines.append("")

    lines.append(": Byte[_rem]")
    return "\n".join(lines) + "\n"


def generate_generic_sddl(stats: Dict[str, Any]) -> str:
    """Generate minimal SDDL for unknown formats."""
    lines = [
        "# ============================================================",
        "# Generic Schema (v1)",
        "# Generated by sddl-generate skill",
        "#",
        "# WARNING: No specific format detected.",
        "# This is a minimal chunked-blob schema.",
        "# Consider using --mode default with nyx instead.",
        "#",
        "# Borrowed baseline idea from nyx/schemas/fasta_packed.sddl:",
        "#   - Magic header pattern",
        "#   - Explicit payload length + padding",
        "# ============================================================",
        "",
        "U32 = UInt32LE",
        "",
        '# Magic "GEN1"',
        "magic      : Byte[4]",
        "data_total : U32",
        "data_pad   : U32",
        "data       : Byte[data_total + data_pad]",
        "",
        ": Byte[_rem]",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Dispatcher
# ---------------------------------------------------------------------------

GENERATORS = {
    "fasta": generate_fasta_sddl,
    "fastq": generate_fastq_sddl,
    "vcf": generate_vcf_sddl,
    "tsv": generate_tsv_sddl,
    "csv": generate_tsv_sddl,
    "generic": generate_generic_sddl,
}


def generate_sddl(stats: Dict[str, Any]) -> str:
    """Generate SDDL content based on analysis stats."""
    fmt = stats.get("format", "generic")
    generator = GENERATORS.get(fmt, generate_generic_sddl)
    return generator(stats)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Generate SDDL schema for a file")
    parser.add_argument("input", type=Path, help="Input file to generate schema for")
    parser.add_argument("--output-dir", type=Path, default=Path("./sddl_out"),
                        help="Output directory (default: ./sddl_out)")
    parser.add_argument("--sample-bytes", type=int, default=10 * 1024 * 1024)
    args = parser.parse_args()

    if not args.input.exists():
        print(f"Error: {args.input} does not exist", file=sys.stderr)
        sys.exit(1)

    # Analyze
    stats = analyze(args.input, args.sample_bytes)

    # Generate
    sddl_content = generate_sddl(stats)

    # Write
    args.output_dir.mkdir(parents=True, exist_ok=True)
    out_path = safe_output_path(args.output_dir, "custom", ".sddl")
    out_path.write_text(sddl_content)
    print(f"Wrote SDDL schema: {out_path}")
    return str(out_path)


if __name__ == "__main__":
    main()
